pipeline {
	agent none
	stages {
		stage('Build the Angular app') {
      dir('seagul') {
        agent {
          dockerfile {
            dir 'build'
          }
        }
        steps {
          sh 'npm i'
          sh 'ng build --prod'
        }
      }
		}
		stage('Do the deployement') {
			agent any
			steps {
				sh 'find .'
			}
		}
	}
}
