pipeline {
  agent any
  stages {
    stage('Build the Angular app') {
      steps {
        sh 'ng build --prod'
      }
    }
    stage('Run the docker compose build and up') {
      steps {
        sh 'docker-compose up --build -d'
      }
    }
  }
}
